version: '3.8'

services:
  db:
    container_name: transactions-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: 'unless-stopped'
    networks:
      - transactions

  live_app:
    container_name: transactions-app
    image: cosmtrek/air
    working_dir: /go/src/transactions
    environment:
      - DB_HOST=transactions-db
    depends_on:
      - db
    networks:
      - transactions

networks:
  transactions:
    name: transactions-network
