version: '3.8'

services:
  db:
    container_name: transactions-db
    image: postgres:14-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${TRANSACTIONS_DB_NAME}
      - POSTGRES_USER=${TRANSACTIONS_DB_USER}
      - POSTGRES_PASSWORD=${TRANSACTIONS_DB_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: 'unless-stopped'
    networks:
      - transactions

  app:
    container_name: transactions-app
    image: transactions:latest
    working_dir: /usr/local/bin
    env_file:
      - ./.env
    environment:
      - TRANSACTIONS_DB_HOST=transactions-db
    depends_on:
      - db
    volumes:
      - source: ./
        target: /usr/local/files
        type: bind
    networks:
      - transactions
    command: transactions -f /usr/local/files/txns.csv

networks:
  transactions:
    name: transactions-network
